<footer>
    <p class="exception">
    <em><strong>If you want to know more, just email us <span id="rightpoint">&#x261b;</span> <a href="mailto:rhettiarachchige@swin.edu.au">EMAIL</a></strong></em><br>&#169;<span id="footer2">by Swinburne University of Technology</span><br>Demonstration:https://youtu.be/r5TDFHqjbE8
    </p>

    <p class="exception">
    <em><strong>Link to the demonstration of assignment </strong></em><a href ="https://youtu.be/SGWX4eTcqF4">Click here</a>
    </p>
</footer>